### PR TITLE
Rework gce plugin

### PR DESCRIPTION
**Pull request by nbttmbrg**
- Using the new/supported gcp Ansible modules
- Allows Internal or External IP
- Now also works on Windows

### CODE REVIEW

**Review by ssbarnea — CHANGES_REQUESTED** [review]
I only took a brief look at this PR but I don't really understand why we would ever need a .go source file and a binary. IMHO, both of them are a no-no, for security and portability point of view.

I really doubt ansible cannot connect to windows hosts without these.

**Comment by nbttmbrg** [comment]
Ansible can connect, this binary is only used to initialize the password : 
https://cloud.google.com/compute/docs/instances/windows/automate-pw-generation

I chose the .go program simply because it worked out of the box for me, I can make the python one work if it's better for you.

**Comment by ssbarnea** [comment]
Before asking you to do it in python, I want to understand where this code needs to run. If it runs with molecule and not on remote host we should do it with python. If the code would be only 10-20 lines it is better to have it inside the library but if is bigger it may make sense to use an external library: if there is one that does that is well maintained. If there is none, just grab the code from https://cloud.google.com/compute/docs/instances/windows/automate-pw-generation#python and add it to the plugin, keeping the license headers obviously.

The only reason i suggested a library is that we could get a free upgrade if needed and avoid the need to patch the driver when the auth method is updated.

I will probably give it a go and attempt to test it myself. As we have two very different types of scenarios (non-windows and windows), it would make sense to create two example scenarios at the root of the repository, so we can easily test them manually by running: `molecule test -s windows` or `molecule test -s linux`

**Comment by nbttmbrg** [comment]
Hello,

I haven't found a library that does it, so I used a Python 3 example and modified it to replace the "sleeps" with change monitoring. I kept the licence header as required. 
To answer your question, this script is executed from the Molecule host, not the instance.

I will add the two example scenarios as you suggested, you can wait for those before accepting this PR, I'll do that tomorrow.

**Review by ssbarnea — APPROVED** [review]
There are several issues with it but I will let it merge like this so we can fix the rest in follow-ups.

**Comment by ssbarnea** [comment]
@nbttmbrg ping me on irc when you have free minutes.

**Pull request merged**
